### ISSUE TITLE
Add ability to host any command

### ISSUE THREAD

**Issue by bleudev** [mbutsk/pyhoster#1]
I suggest to add ability to host any command provided in host.yml (how in `docker` with Dockerfile). Example:

host.yml:
```yml
# Directory where to exec commands
cwd:
  ~/dev/my_site

# Install depens and run dev version
exec:
  - npm install
  - npm run dev
```
